#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VotingPoll.Resource", IsApplication=true)]

namespace VotingPoll
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001c
			public const int ButtonLayout = 2131034140;
			
			// aapt resource value: 0x7f050011
			public const int Choice1 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int Choice1EditText = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int Choice1Layout = 2131034128;
			
			// aapt resource value: 0x7f050014
			public const int Choice2 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int Choice2EditText = 2131034133;
			
			// aapt resource value: 0x7f050013
			public const int Choice2Layout = 2131034131;
			
			// aapt resource value: 0x7f050017
			public const int Choice3 = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int Choice3EditText = 2131034136;
			
			// aapt resource value: 0x7f050016
			public const int Choice3Layout = 2131034134;
			
			// aapt resource value: 0x7f05001a
			public const int Choice4 = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int Choice4EditText = 2131034139;
			
			// aapt resource value: 0x7f050019
			public const int Choice4Layout = 2131034137;
			
			// aapt resource value: 0x7f050004
			public const int ChoicesEditText = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int ChoicesLayout = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int CreateChoicesButton = 2131034117;
			
			// aapt resource value: 0x7f050020
			public const int CreatePollButton = 2131034144;
			
			// aapt resource value: 0x7f05000d
			public const int CreateResponsesCreatePollButton = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int CurrentPollQuestion = 2131034126;
			
			// aapt resource value: 0x7f050002
			public const int NumberText = 2131034114;
			
			// aapt resource value: 0x7f050021
			public const int PollListView = 2131034145;
			
			// aapt resource value: 0x7f050001
			public const int QuestionEditText = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int QuestionText = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int Response1 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int Response2 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int Response3 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int Response4 = 2131034124;
			
			// aapt resource value: 0x7f050008
			public const int ResponsesLinearLayout = 2131034120;
			
			// aapt resource value: 0x7f05001e
			public const int SubmitResponsesButton = 2131034142;
			
			// aapt resource value: 0x7f050007
			public const int Title = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int TitleText = 2131034112;
			
			// aapt resource value: 0x7f05001d
			public const int ViewChartButton = 2131034141;
			
			// aapt resource value: 0x7f05001f
			public const int ViewPollsButton = 2131034143;
			
			// aapt resource value: 0x7f05000f
			public const int textView2 = 2131034127;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CreatePollActivityLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CreateResponsesLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CurrentPollLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ViewChartLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ViewPollsLayout = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
